[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aicodec"
version = "0.1.0"
description = "A set of tools to encode and decode file structures into JSON for communicating with a llm."
readme = "README.md"
license = { text = "MIT License" }
authors = [
  { email = "steviekra@gmail.com" },
]
dependencies = [
    "jsonschema",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
]

# This section makes your scripts available as command-line tools
[project.scripts]
ai-encode = "aicodec.encoder:main"
ai-decode = "aicodec.decoder:main"