name: Publish Docs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # Needed to push to gh-pages branch

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install documentation dependencies
        run: pip install mkdocs mkdocs-material

      - name: Deploy docs
        run: mkdocs gh-deploy --force
